name: PR

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop
      - release/*

permissions:
  contents: read
  packages: read

run-name: ${{ github.event_name == 'pull_request' && format('[PR] - {1} {0}',  github.event.pull_request.number, github.event.pull_request.title) || format('[MANUAL] - Run on {0} branch', github.event.pull_request.number, github.ref_name) }}

jobs:
  ci:
    uses: IronyxLabs/ironyx-scripts/.github/workflows/svelte_pr-pipeline.yaml@v1
    with:
      sonar-project_key: IronyxLabs_ironyx-service-index-ui
    secrets:
      testspace-token: ${{ secrets.TESTSPACE_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
